* COMMENT Syntax
** Variable
   =new <name> [: <type>] = <expr>=
** Custom Types
*** Enum
   #+begin_src 
   enum[generics] <name>[generics] {
     name [(<name>: [annotation] <type>, ...)]
     ...
   }
   #+end_src
*** Struct
   #+begin_src 
   struct[generics] <name>[generics] {
     <field>: [annotation] <type>
     ...
   }
   #+end_src
*** Data
   #+begin_src 
   data <name> {
     [groups: <name>, ...] // These are constraint groups such as for composite keys
     <field>: ["maybe"] <type> [relations] [constraints]
     ...
   }
   #+end_src
**** relationships
     - identifier
     - table=>field [conflict resolution]
**** constraints
     - unique
     - validator: <window pipe name>
     - default: <value>
     - [group:]index
** Function
   =fn <name>(<arg>: [annotation] <type>, ...) [-> [name] [annotation] <type>] {...}=
** Pipe
   Window pipe: =pipe (<name>: [annotation] <type>) | <name>(<arg>: [annotation] <type>) [-> [name] [annotation] <type>] {...}=
   Grabby pipe: =pipe (<name>: [annotation] <type>) |> <name>(<arg>: [annotation] <type>) [-> [name] [annotation] <type>] {...}=
   Method pipe:
   #+begin_src 
   impl["["generic [: <interface>], ..."]"] <interface>["<"<parameter_type>">"]:
   pipe ...
   #+end_src
** Interfaces
   #+begin_src 
   interface[generics] <name>[<generics>] {
     pipe (self) | <name> ...
     pipe (self) |> <name> ...
   }
   #+end_src
** Type Annotations
   Types can be annotation. You can use words or symbols before the type (the
   formatter will convert symbols to types anyway, but it's faster).

   - ? -> maybe  ; variable may be void
   - ! -> failing ; variable may be an error instead
   - & -> ref ; read-only pointer
   - * -> mut ; read-write pointer
   - = -> into ; can be converted into that type
   - > -> interated ; has a =| next= pipe
   - # -> locked ; variable is behind a mutex
   - @ -> writable ; variable is a locked read-write pointer to a mutexed variable
   - ~ -> readable ; variable is a locked read-only pointer to a mutexed variable

   Example:

   =fn printStuff(stuff: =string) { stuff | into<string> | speak }=

   or

   =fn printStuff(stuff: into string) { stuff | into<string> | speak }=
** Operators
*** Error resolution
    Checks if a failing value is an error, and if so wraps that error in the
    argument string and returns that instead.

    This is a shorthand version of some pipe I haven't named yet. Something like
    =okay <string>= or =error <string>= or something.

    #+begin_src
      fn doStuff() -> failing void {...}

      fn main() -> failing string {
		doStuff() ?? failed to do stuff
		return "success"
      }
    #+end_src

    If you choose not to do this inside a pipe, the pipe will automatically skip
    all steps after the failure untill a =??= or =okay= (or whatever the pipe
    version of =??= is going to be) are called. Basically, pipes are always
    automatically monadic.
*** Debug prints
    To print a variable at a given line when building with a --debug flag or
    something, use =___= at the end of the line

    #+begin_src
      value
      | pipe1 arg ___                             // Prints the result of this pipe
      | pipe2 args args args ___ ?? Failed pipe 2 // Will print the error or the value
      | pipe3 ?? Failed pipe 3 ___                // Will NOT print, but return an error with '___' in it
    #+end_src
* Syntax
** Variables
   snakeCase, even when exported.
*** Stack
    Declaration:
    =new name = Expr= or =new name: Type = Expr=
    with multiple:
    =new name1, name2 = Expr= or =new name1: Type, name2: Type ...= or =new name1 name2: Type = ...=

    Reassignment:
    =old name = Expr=
    with multiple:
    =old name1, name2 = Expr=

    Mixed declaration and reassignment:
    =new newName1, newName2, old oldName = Expr=
*** Heap
    Declaration: =heap name = Expr= where =name= is a pointer, always. Otherwise
    it's the same.
*** Editing
    Field editing:
    =set name.field = Expr=

    Reference editing (only works for =mut= references or owned =ptr= pointers):
    =set pointer << Expr=
** Data Types
   CamelCase
*** Void
    =void= is a keyword which is both a value and a type where:

    =void (variable): void (type)=
*** Simple
   Aliases: =alias NewType OldType=
   The =NewType= is identical in every way, it's an /alias/.

   Simple new types: =type NewType OldType=
   The =NewType= has the same structure and associated procedures, but you may
   define new procedures and implementations for it without modifying the
   original.
*** Enums
    #+begin_src text
      enum NewEnum {
      	variant1
      	variant2(InnerType)
      	variant3 { field1: Type, field2: Type }
      }
    #+end_src

    Accessing variants is done through the =--= operation, so =--variant1=. If
    there are two or more =enum=​s with the same variant, we try to intuit from
    the context. This may be impossible or you may want to avoid doing it, in
    which case you can specify =NewEnum=>variant2(innerTypeInstance)=.
*** Structs
    #+begin_src text
      struct NewStruct {
      	field1: Type
      	field2: Type
      }
    #+end_src

    If the struct contains a reference, the reference's scope must be specified.
    The struct becomes scoped, the scope is given a name, and the name is used
    as a parameter to the =ref= or =mut= keywords:

    #+begin_src text
      struct RefWrapper scope s1, s2 {
      	refField1: ref<s1> int,
      	refField2: mut<s2> bool,
      }

      new integer = 1;
      new boolean = true;

      // No need to specify when creating the struct directly.
      RefWrapper {
      	refField1: &integer,
      	refField2: *bool,
      }

      // But we MUST specify when returning from procedures using the @ operator.
      function :: integer: int, boolean: mut bool -> RefWrapper<@integer, @boolean>
      	return RefWrapper { refField1: &integer, refField2: boolean, };
    #+end_src

    Note we can use both owned and referenced types as arguments to =function=.
    For references (=boolean=), we'll just take the scope of the reference and
    copy it for the =RefWrapper= return value. For owned values (=integer=),
    we'll first move the value to the heap (which will make it a =ptr= rather
    than a =mut= or a =ref=, and =ptr=​s are owned, not references. That means
    =@boolean= is the scope of the owning variable in the caller, but =@integer=
    is a scope synonymous with this instance of =RefWrapper=.
*** TODO Data
*** Generics
    Generics all have a scope where the letter or word means "some generic
    type." If a function uses generics, those generics exist only within that
    function. Pretty obvious. The first use of a generic looks like =#A= which
    says "I'm using an unconstrained generic type =A=." Subsequently, you can
    just use =A= in the same function.

    Example:
    #+begin_src text
      // Defining a function which takes two arguments and makes a list of them.
      // The arguments are both of the same (generic) type.
      someFunc := a: #A, b: A -> ...A = [a, b]
    #+end_src
*** Type Constraints
    A type may be constrained by some generic type.
    #+begin_src text
      struct NewType<A> {
      	field: A,
      }
    #+end_src
    
    In type definitions, you don't need to add the =#= in front of =A= because
    it's assumed that =A= is /always/ a generic. When using the type later, you
    /do/ need the =#=. This is to avoid the compiler figuring out whether this
    instance of =NewType= is constrained by a generic type called =A= and some
    real type defined elsewhere that happens to also be called =A=.

    #+begin_src text
      type B string

      someFunc := arg1: NewType<#A>, arg2: NewType<A>, arg3: NewType<B> ...
    #+end_src

    This declares a generic type =A=, constraints =arg1= and =arg2= by it, but
    =arg3= is constraint by a real type =B=.
*** Classes
    A generic type may be limited to a class of types, i.e., to an interface.
    Just saying =#A= means /any type/. If instead we need /any numeric type/, we
    need to declare =A= to belong to a class:

    #+begin_src text
      interface Adder {
      	// This is a pipe definition that adds the base (me, which is the Adder implementation) and the argument:
      	add | other: Implement -> int
      }


      // Let's leave the Adder implementation aside for now.

      addThree [A: _Adder] := a b c: A -> int = // function body
    #+end_src

    Here we're defining a type class =A= which implements =Adder=. In this case
    it's redundant because you could just write =a b c: Adder=. But when doing a
    type constraint, this is useful:

    #+begin_src text
      append [A: _Adder] := list: List<A>, newVal: A = // function body
    #+end_src
*** Special Types
**** Program
     =Program= is a built-in type which refers to a series of operations
     surrounded by ={ }=. The operations are executed in sequence, and return
     nothing.

     This is to avoid passing closures with no arguments and return values all
     the time, but essentially this holds: =alias Program () >> _=.
**** Embedded
     The =Embedded= type is a sort of =Program= but it is executed on the
     caller, i.e., it is embedded in the caller rather in the executing
     procedure. In practice this is done so that you can return from function A
     from within function B called inside A.

     This is a classic example:

     #+begin_src text
       === Executes `program` if self is `void`, returns self ===
       maybe #T | ifno :: program: Embedded -> T
       	if me | isvoid {
       		program | execute;
       	}
       	return me;


       // In actual code:

       new someVar = Expr | ifno return error;
     #+end_src

     In the above example we evaluate =Expr= whose type is =maybe Something=,
     then we inspect the =maybe=. If it's =void=, we execute =return error;= IN
     THE CURRENT FUNCTION (hence the embeddedness).

     An =Embedded= block is either a return (=return=, =break=, =continue=,
     =error=, =success=, and similar, followed by maybe an expression and then a
     =;=), or a ={ }= Program. Be careful - if there is more stuff following
     rather than an immediate =;=, you must use braces, otherwise all that
     following stuff is taken to be a part of the returned expression.
*** Type Operators
    Some types deserve special constructors.

    - strings are surrounded by "...".
    - characters are '.'
    - formatted strings are `...{}...` which creates a closure that accepts as
      many arguments as there are ={}=​s, all of which must implement
      =_ToString=.
    - lists over =#T= are denoted as =...T=.
*** TODO References and Pointers, Stack and Heap
*** Annotations
    Types can be augmented via the use of type annotations. An annotation does
    not create a new type but rather enables some extra functionality which is
    natively built into every type. Annotations have names and many can be
    represented via symbols right in front of the type name.

    You can only use annotations in type usage, not type definitions.
**** Into
     A value is of type =into T= if there is a known operation which turns that
     variable into type =T=. Type =T= already satisfies this without change.
     Closures =() >> T= are evaluated.

     =into= adds laziness to the type. For example: =Iterator<#T>: into ...T=.
     Note that the itererator doesn't need to be converted into a list, it
     already is of type =into list=.

     As soon as =into T= type is used as =T= for the first time, the registered
     operation is performed without any extra syntax.

     Symbol: into T == =T
**** Fn
     A value of type =fn T= has a registered operation which produces =T=
     indefinitely. It's usually a function which gets us some value of type =T=
     (not always the same value) whenever we call it. Of course, =T: fn T=.

     Symbol: fn T == >> T
**** Iterated
     Iterated types are types which implement the =Iterator= interface. They
     have a =next= procedure which produces =maybe T=.

     Symbol: iter T == >T
**** Maybe
     Maybe is a nullability wrapper. A =maybe T= is either =void= or =T=. This
     isn't an enum because that's too verbose. A series of built-in procedures
     exist to work with =maybe= types, such as =ifno=, =forceInner=, =getor=,
     etc.

     Symbol: maybe T == ?T
**** Failing
     Failing is a monad. A =failing T= is either a T or an =Error= type.

     To return a success, use =success Expr;=. To return a failure, use =error
     "message"=.

     Symbol: failaing T == !T
**** Synced
     Mutexes don't exit in Cease. They are built-in via the =synced= type
     annotation. A =synced T= cannot be read until it's opened with either
     =rlock= for read mutex lock, or =wlock= for writes. This operation returns
     the appropriate reference to the value, and is unlocked either with =unlock
     <var>= or when =<var>= goes out of scope.

     Symbol: synced T == #T
**** Ptr, Mut, Ref
     These annotations denote pointers.

     A =ptr= is a heap pointer owned by the current scope. It will be =free=​ed
     when the scope ends.

     A =mut= is a pointer owned by a parent scope. The data can be edited.

     A =ref= is a pointer owned by a parent scope. The data cannot be edited.

     Symbols:
     - ptr T =​= ~T
     - mut T =​= *T
     - ref T =​= &T
** Procedures
*** TODO Functions
    # Finish him (I mean this)

    Multiline:
    #+begin_src text
      functionName := argument1: Type1, argument2 argument3: Type2 -> ReturnType
      	procedure
      	(return) value
      $$$
    #+end_src

    Oneline:
    #+begin_src text
      funcName := arg1: Type -> ReturnType = Expr
    #+end_src

    In this oneline example, the function may or may not return something.
    Functions which return nothing implicitly return the =void= type. If =Expr=
    returns the expected type, that's taken to be the return value. If the
    function returns =void= but =Expr= evaluates to some other type, the =Expr=
    value is /not/ returned.

    Functions have a type; the above would be =funcName: (Type) >> ReturnType=.
*** TODO Pipes
*** TODO Closures
** TODO Blocks
   (if, switch, plain {})
** TODO Interfaces
** TODO Package (export) management
