* COMMENT Syntax
** Variable
   =new <name> [: <type>] = <expr>=
** Custom types
*** Enum
   #+begin_src 
   enum[generics] <name>[generics] {
     name [(<name>: [annotation] <type>, ...)]
     ...
   }
   #+end_src
*** Struct
   #+begin_src 
   struct[generics] <name>[generics] {
     <field>: [annotation] <type>
     ...
   }
   #+end_src
*** Data
   #+begin_src 
   data <name> {
     [groups: <name>, ...] // These are constraint groups such as for composite keys
     <field>: ["maybe"] <type> [relations] [constraints]
     ...
   }
   #+end_src
**** relationships
     - identifier
     - table=>field [conflict resolution]
**** constraints
     - unique
     - validator: <window pipe name>
     - default: <value>
     - [group:]index
** Function
   =fn <name>(<arg>: [annotation] <type>, ...) [-> [name] [annotation] <type>] {...}=
** Pipe
   Window pipe: =pipe (<name>: [annotation] <type>) | <name>(<arg>: [annotation] <type>) [-> [name] [annotation] <type>] {...}=
   Grabby pipe: =pipe (<name>: [annotation] <type>) |> <name>(<arg>: [annotation] <type>) [-> [name] [annotation] <type>] {...}=
   Method pipe:
   #+begin_src 
   impl["["generic [: <interface>], ..."]"] <interface>["<"<parameter_type>">"]:
   pipe ...
   #+end_src
** Interfaces
   #+begin_src 
   interface[generics] <name>[<generics>] {
     pipe (self) | <name> ...
     pipe (self) |> <name> ...
   }
   #+end_src
** Type Annotations
   Types can be annotation. You can use words or symbols before the type (the
   formatter will convert symbols to types anyway, but it's faster).

   - ? -> maybe  ; variable may be void
   - ! -> failing ; variable may be an error instead
   - & -> ref ; read-only pointer
   - * -> mut ; read-write pointer
   - = -> into ; can be converted into that type
   - > -> interated ; has a =| next= pipe
   - # -> locked ; variable is behind a mutex
   - @ -> writable ; variable is a locked read-write pointer to a mutexed variable
   - ~ -> readable ; variable is a locked read-only pointer to a mutexed variable

   Example:

   =fn printStuff(stuff: =string) { stuff | into<string> | speak }=

   or

   =fn printStuff(stuff: into string) { stuff | into<string> | speak }=
** Operators
*** Error resolution
    Checks if a failing value is an error, and if so wraps that error in the
    argument string and returns that instead.

    This is a shorthand version of some pipe I haven't named yet. Something like
    =okay <string>= or =error <string>= or something.

    #+begin_src
      fn doStuff() -> failing void {...}

      fn main() -> failing string {
		doStuff() ?? failed to do stuff
		return "success"
      }
    #+end_src

    If you choose not to do this inside a pipe, the pipe will automatically skip
    all steps after the failure untill a =??= or =okay= (or whatever the pipe
    version of =??= is going to be) are called. Basically, pipes are always
    automatically monadic.
*** Debug prints
    To print a variable at a given line when building with a --debug flag or
    something, use =___= at the end of the line

    #+begin_src
      value
      | pipe1 arg ___                             // Prints the result of this pipe
      | pipe2 args args args ___ ?? Failed pipe 2 // Will print the error or the value
      | pipe3 ?? Failed pipe 3 ___                // Will NOT print, but return an error with '___' in it
    #+end_src
* Syntax
** Variables
   SnakeCase, even when exported.

   Declaration:
   =new name = Expr= or =new name: Type = Expr=
   with multiple:
   =new name1, name2 = Expr= or =new name1: Type, name2: Type ...= or =new name1 name2: Type = ...=

   Reassignment:
   =old name = Expr=
   with multiple:
   =old name1, name2 = Expr=

   Mixed declaration and reassignment:
   =new newName1, newName2, old oldName = Expr=

   Field editing:
   =set name.field = Expr=
** Data Types
   CamelCase.
*** Simple
   Aliases: =alias NewType OldType=
   The =NewType= is identical in every way, it's an /alias/.

   Simple new types: =type NewType OldType=
   The =NewType= has the same structure and functions, but you may define new functions for it.
*** Enums
    #+begin_src text
      enum NewEnum {
      	Variant1
      	Variant2(InnerType)
      	Variant3 { field1: Type, field2: Type}
      }
    #+end_src
*** Structs
    #+begin_src text
      struct NewStruct {
      	field1: Type
      	field2: Type
      }
    #+end_src
*** TODO Data
*** Generics
    Generics all have a scope. If a function uses generics, those generics exist
    only within that function. Pretty obvious. The first use of a generic looks
    like =#A= which says "I'm using an unconstrained generic type =A=.
    Subsequently, you can just use =A= in the same function.

    Example:
    #+begin_src text
      // Defining a function which takes two arguments and makes a list of them.
      // The arguments are both of the same (generic) type.
      someFunc := a: #A, b: A -> ...A = [a, b]
    #+end_src
*** Type Constraints
    A type may be constrained by some generic type.
    #+begin_src text
      struct NewType<A> {
      	field: A,
      }
    #+end_src

    In type definitions, you don't need to add the =#= in front of =A= because
    it's assumed that =A= is /always/ a generic. When using the type later, you
    /do/ need the =#=. This is to avoid the compiler figuring out whether this
    instance of =NewType= is constrained by a generic type called =A= and some
    real type defined elsewhere that happens to also be called =A=.

    #+begin_src text
      type B string

      someFunc := arg1: NewType<#A>, arg2: NewType<A>, arg3: NewType<B> ...
    #+end_src

    This declares a generic type =A=, constraints =arg1= and =arg2= by it, but
    =arg3= is constraint by a real type =B=.
*** Classes
    A generic type may be limited to a class of types, i.e., to an interface.
    Just saying =#A= means /any type/. If instead we need /any numeric type/, we
    need to declare =A= to belong to a class:

    #+begin_src text
      interface Adder {
      	// This is a pipe definition that adds the base (me, which is the Adder implementation) and the argument:
      	add | other: Implement -> int
      }


      // Let's leave the Adder implementation aside for now.

      addThree [A :: Adder] := a b c: A -> int = // function body
    #+end_src

    Here we're defining a type class =A= which implements =Adder=. In this case
    it's redundant because you could just write =a b c: Adder=. But when doing a
    type constraint, this is useful:

    #+begin_src text
      append [A :: Adder] := list: List<A>, newVal: A = // function body
    #+end_src
** Procedures
*** Functions
    Multiline:
    #+begin_src text
      functionName := argument1: Type1, argument2 argument3: Type2 -> ReturnType
      	procedure
      	(return) value
      $$$
    #+end_src

    Oneline:
    #+begin_src text
      funcName := arg1: Type -> ReturnType = Expr
    #+end_src

    In this oneline example, the function may or may not return something.
    Functions which return nothing implicitly return the =void= type. If =Expr=
    returns the expected type, that's taken to be the return value. If the
    function returns =void= but =Expr= evaluates to some other type, the =Expr=
    value is /not/ returned.

    Functions have a type; the above would be =funcName: (Type) >> ReturnType=.
*** TODO Pipes
*** TODO Closures
** TODO Interfaces
** TODO Package (export) management
