In Cease, nearly everything is an expression. The only exceptions are modules
(as in the files and directories) and code blocks which manage them (but not
code blocks which import them).

Expressions evaluate to a value which has a type. Types are well known at
compilation time. Special expressions (such as plain ={}= scopes) evaluate to the
=void= type, but otherwise most code blocks return something useful.

Expressions have =terminators= (expressed here as single-quoted strings) which
must appear as they are shown in the code, and literals - predefined types of
terminators which are not always so simple to express.

* Literal Classes
  Literals come in these flavours:

  - BOOL: =true= or =false=
  - STRING: A block of text, quoted
  - NUMBER: Any of the number formats
  - NAME: Name of a named expression (e.g. variable, function, ...)
* [0/3] Expression
  Expressions which evaluate to some mathematical value, either of the =BOOL= or
  =NUMBER= literal class.

  #+begin_example
     expression          ::= pipeCall
     pipeCall            ::= equality ( ('|' | '|>') functionCall functionCall* )* ( NEWLINE | EOF | '{' | '}' | ')' | ',' | ';' )
     equality            ::= logic ( ('==' | '!=') logic )?
     logic               ::= comparison ( ('&&' | '||' | 'and' | 'or' | 'xor' | 'nand') comparison)?
     comparison          ::= sum ( ('<' | '<=' | '>' | '>=') sum )?
     sum                 ::= product ( ('+' | '-') product )*
     product             ::= binary_arithmetic ( ('*' | '/') binary_arithmetic )*
     binary_arithmetic   ::= unary ( ('^&' | '^|') unary )?
     unary               ::= ('!' | '-')? functionCall
     functionCall        ::= base ( '(' ( expression ( ',' expression )* )* ')' )*
     base                ::= BOOL | STRING | CHAR | NUMBER | 'void' | NAME | '(' expression ')'
  #+end_example
** TODO Block
   Code blocks, standard programming paradigms like a for loop, if, etc. There
   are also expressions in Cease.
** Exit
   Keywords which exit the current block with a value.

   #+begin_example
   exit ::= ( 'return' | 'break' | 'continue' ) expression
   #+end_example
** Builtin
   Built-in command for easy life.

   #+begin_example
   builtin ::= ( 'unlock' | 'rlock' | 'wlock' ) LITERAL
   #+end_example
* TODO Statements
* TODO Abstract Syntax Tree (AST)
* COMMENT File config
# Local variables:
# eval: (auto-fill-mode 1)
# End:
